name: towfix_service
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  google_fonts: ^5.1.0
  riverpod: ^2.4.0
  flutter_svg: ^2.0.7
  go_router: ^9.0.0
  firebase_auth: ^4.9.0

  # media
  camera: ^0.10.4
  camerawesome: ^1.2.1
  image_picker: ^0.8.4+4
  riverpod_annotation: ^2.1.5
  ui_common:
    path: packages/ui_common/


  permission_handler: ^10.2.0
  hive_flutter: ^1.1.0
  hive: 2.2.3  
  dio: ^5.3.2
  cloud_firestore: ^4.9.1
  intl: ^0.18.1
  flutter_riverpod: ^2.4.0
  dartz: ^0.10.1
  firebase_storage: ^11.2.6
  font_awesome_flutter: ^10.5.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.0.4
  mockito: ^5.0.15
  #generate flutter hive type adapters
  # generate splash screens
  flutter_native_splash: ^2.0.5
  # generate launcher icons
  flutter_launcher_icons: ^0.9.3
  # Code generation
  json_serializable: ^6.1.4
  freezed: ^2.1.0+1
  intl_phone_field: ^3.2.0
  pinput: ^3.0.0
  hive_generator: ^2.0.1

  riverpod_generator: ^2.3.2



  # // camera





# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
 
  assets:
    - assets/images/
    - assets/static/
    - assets/svg/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
