// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7BhvykSsMoBpOXmJoJMO1i3aWhHZFO08',
    appId: '1:146354161007:web:acb9fba66aa36dff4b149a',
    messagingSenderId: '146354161007',
    projectId: 'tow-fix',
    authDomain: 'tow-fix.firebaseapp.com',
    storageBucket: 'tow-fix.appspot.com',
    measurementId: 'G-TGDQL4D9FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLMH4uJAneCB7z6GGN1OBzZrtBMXzlVds',
    appId: '1:146354161007:android:8b8e8b75a42b996e4b149a',
    messagingSenderId: '146354161007',
    projectId: 'tow-fix',
    storageBucket: 'tow-fix.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANeBkyqRBHtt9_3heyna0qdTZwhOVERYk',
    appId: '1:146354161007:ios:f8682193761cffa14b149a',
    messagingSenderId: '146354161007',
    projectId: 'tow-fix',
    storageBucket: 'tow-fix.appspot.com',
    iosClientId: '146354161007-364t94cjl4oagd854q6pgn4l0i854mlv.apps.googleusercontent.com',
    iosBundleId: 'com.example.towfixService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANeBkyqRBHtt9_3heyna0qdTZwhOVERYk',
    appId: '1:146354161007:ios:681fb98734d7fb764b149a',
    messagingSenderId: '146354161007',
    projectId: 'tow-fix',
    storageBucket: 'tow-fix.appspot.com',
    iosClientId: '146354161007-frd944bfctq0g7ac87pq5mpfh07dsmm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.towfixService.RunnerTests',
  );
}
