// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8_tAVl0x0FOfKig_G1P5U048D8KqqlGI',
    appId: '1:361987235930:web:6193e12221af613697b863',
    messagingSenderId: '361987235930',
    projectId: 'towfix-abd8c',
    authDomain: 'towfix-abd8c.firebaseapp.com',
    storageBucket: 'towfix-abd8c.appspot.com',
    measurementId: 'G-YSK2XN6LQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeK2Vtg1aIdC5DSSi7vbeLNC5X60iQjSQ',
    appId: '1:361987235930:android:a95e687f95ebb38b97b863',
    messagingSenderId: '361987235930',
    projectId: 'towfix-abd8c',
    storageBucket: 'towfix-abd8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8jddxR1QJnWGjzcIFBxZTKVEhT02dv0c',
    appId: '1:361987235930:ios:13f981fb6c7b63a897b863',
    messagingSenderId: '361987235930',
    projectId: 'towfix-abd8c',
    storageBucket: 'towfix-abd8c.appspot.com',
    iosClientId: '361987235930-e1m0vmsmr0oop60ik4rd6uvtbqf5d2iv.apps.googleusercontent.com',
    iosBundleId: 'com.example.towfixService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8jddxR1QJnWGjzcIFBxZTKVEhT02dv0c',
    appId: '1:361987235930:ios:568b31f2d840c09197b863',
    messagingSenderId: '361987235930',
    projectId: 'towfix-abd8c',
    storageBucket: 'towfix-abd8c.appspot.com',
    iosClientId: '361987235930-c60i6agmgjdme5mqme803gmskjcmd8tn.apps.googleusercontent.com',
    iosBundleId: 'com.example.towfixService.RunnerTests',
  );
}
